export interface marketDataType {
ath: object;
ath_change_percentage: object;
ath_date: object;
atl: object;
atl_change_percentage: object;
atl_date: object;
circulating_supply: number;
current_price: {inr: number, usd: number};
fdv_to_tvl_ratio: null;
fully_diluted_valuation: object;
high_24h: object;
last_updated: string;
low_24h: object;
market_cap: {inr: number, usd: number};
market_cap_change_24h: number;
market_cap_change_24h_in_currency: object;
market_cap_change_percentage_24h: number;
market_cap_change_percentage_24h_in_currency: object;
market_cap_rank: number;
max_supply: number;
mcap_to_tvl_ratio: null;
price_change_24h: number;
price_change_24h_in_currency: object;
price_change_percentage_1h_in_currency: object;
price_change_percentage_1y: number;
price_change_percentage_1y_in_currency: object;
price_change_percentage_7d: number;
price_change_percentage_7d_in_currency: object;
price_change_percentage_14d: number;
price_change_percentage_14d_in_currency: object;
price_change_percentage_24h: number;
price_change_percentage_24h_in_currency: object;
price_change_percentage_30d: number;
price_change_percentage_30d_in_currency: object;
price_change_percentage_60d: number;
price_change_percentage_60d_in_currency: object;
price_change_percentage_200d: number;
price_change_percentage_200d_in_currency: object;
roi: null;
total_supply: number;
total_value_locked: null;
total_volume: number;
}